api:
  name: oscar-api
  protocol: http
  hostname: localhost
  port: 3000
  pathname: /

database:
  type: mysql
  host: localhost
  user: your_db_user
  password: your_db_password
  name: db_name

ranking:
  numVars: 100  # how many items to use for the MLR ranking
  numKeywords: 100 # max number of keywords to include in ranking
