name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup database
        run: |
          psql -h localhost -U postgres -d postgres -f ./packages/api/test/mocks/postgres/items.sql
          psql -h localhost -U postgres -d postgres -f ./packages/api/test/mocks/postgres/users.sql
        env:
          PGPASSWORD: test
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: |
          cp ./packages/api/.env.example ./packages/api/.env
          npm run test
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
